// This file is automatically generated. Do not edit it directly.
import { createMiddleware } from '@tanstack/react-start'
import { getRequest } from '@tanstack/react-start/server'
import { createClient } from '@supabase/supabase-js'
import type { Database } from './types'



function isNewSupabaseApiKey(value: string): boolean {
  return value.startsWith('sb_publishable_') || value.startsWith('sb_secret_');
}

function createSupabaseFetch(supabaseKey: string): typeof fetch {
  return (input, init) => {
    const headers = new Headers(
      typeof Request !== 'undefined' && input instanceof Request ? input.headers : undefined,
    );

    if (init?.headers) {
      new Headers(init.headers).forEach((value, key) => headers.set(key, value));
    }

    // New Supabase API keys are opaque strings, not bearer JWTs.
    if (isNewSupabaseApiKey(supabaseKey) && headers.get('Authorization') === `Bearer ${supabaseKey}`) {
      headers.delete('Authorization');
    }

    headers.set('apikey', supabaseKey);
    return fetch(input, { ...init, headers });
  };
}

export const requireSupabaseAuth = createMiddleware({ type: 'function' }).server(
  async ({ next }) => {
    
    const SUPABASE_URL = process.env.SUPABASE_URL;
    const SUPABASE_PUBLISHABLE_KEY = process.env.SUPABASE_PUBLISHABLE_KEY;

    if (!SUPABASE_URL || !SUPABASE_PUBLISHABLE_KEY) {
      console.error('[Supabase] Missing SUPABASE_URL or SUPABASE_PUBLISHABLE_KEY');
      throw new Error('Session expirée. Reconnecte-toi.');
    }
    
    const request = getRequest();

    if (!request?.headers) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    const authHeader = request.headers.get('authorization');

    if (!authHeader) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    if (!authHeader.startsWith('Bearer ')) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    const token = authHeader.replace('Bearer ', '');
    if (!token) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    if (token.split('.').length !== 3) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    const supabase = createClient<Database>(
      SUPABASE_URL!,
      SUPABASE_PUBLISHABLE_KEY!,
      {
        global: {
          fetch: createSupabaseFetch(SUPABASE_PUBLISHABLE_KEY!),
          headers: {
            Authorization: `Bearer ${token}`,
          },
        },
        auth: {
          storage: undefined,
          persistSession: false,
          autoRefreshToken: false,
        },
      }
    );

    const { data, error } = await supabase.auth.getClaims(token);
    if (error || !data?.claims) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    if (!data.claims.sub) {
      throw new Error('Session expirée. Reconnecte-toi.');
    }

    return next({
      context: {
        supabase,
        userId: data.claims.sub,
        claims: data.claims,
      },
    });
  },
);
